-- Operational schema, version 1 (SQLite model v49). Apply with an owner role.

BEGIN;

CREATE SCHEMA nerve_pg;

SET LOCAL search_path = nerve_pg, public;

CREATE TABLE storage_version(version integer PRIMARY KEY);

INSERT INTO storage_version VALUES (1);

CREATE TABLE scopes (
    _scope TEXT PRIMARY KEY DEFAULT current_setting('nerve.scope')
);
ALTER TABLE scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE scopes FORCE ROW LEVEL SECURITY;
CREATE POLICY scope ON scopes USING (_scope=current_setting('nerve.scope',true));

CREATE TABLE accounts (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    actor_id TEXT NOT NULL,
    username          TEXT,
    credential_source TEXT NOT NULL
                      CHECK (credential_source IN ('config', 'local', 'none')),
    credential        TEXT,
    enabled           INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    created_at        TEXT NOT NULL,
    CHECK ((credential_source = 'local' AND credential IS NOT NULL)
           OR (credential_source IN ('config', 'none') AND credential IS NULL))
,
    PRIMARY KEY (_scope, id),
    UNIQUE (_scope, actor_id)
);

CREATE TABLE actor_refs (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT NOT NULL,


    kind         TEXT NOT NULL,
    display_name TEXT,
    created_at   TEXT NOT NULL
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE channel_sessions (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    channel_key TEXT,
    session_id TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, channel_key)
);

CREATE TABLE consumer_cursors (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    consumer TEXT NOT NULL,
    source TEXT NOT NULL,
    cursor_seq INTEGER NOT NULL DEFAULT 0,
    session_id TEXT,
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    expires_at TEXT,
    PRIMARY KEY (_scope, consumer, source)
);

CREATE TABLE cron_logs (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    job_id TEXT NOT NULL,
    started_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    finished_at TEXT,
    status TEXT,
    output TEXT,
    error TEXT
, session_id TEXT,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE instance_secrets (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    name TEXT,
    value TEXT NOT NULL
,
    PRIMARY KEY (_scope, name)
);

CREATE TABLE instance_setup (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER CHECK (id = 1),
    completed_at TEXT NOT NULL
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE mcp_servers (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    name TEXT,
    type TEXT NOT NULL DEFAULT 'stdio',
    enabled INTEGER DEFAULT 1,
    tool_count INTEGER DEFAULT 0,
    first_seen_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    last_seen_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, name)
);

CREATE TABLE mcp_tool_usage (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    server_name TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    session_id TEXT,
    duration_ms INTEGER,
    success INTEGER DEFAULT 1,
    error TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE memu_audit_log (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    timestamp TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    source TEXT,
    details TEXT
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE messages (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT,
    thinking TEXT,
    blocks TEXT,
    created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    channel TEXT
, external_id TEXT, native_turn_id TEXT, actor_id TEXT,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE notification_silences (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    pattern          TEXT NOT NULL,
    action           TEXT NOT NULL DEFAULT 'silence',
    reason           TEXT DEFAULT '',
    created_by       TEXT DEFAULT '',
    created_at       TEXT NOT NULL,
    expires_at       TEXT,
    hit_count        INTEGER DEFAULT 0,
    last_hit_at      TEXT,
    override_count   INTEGER DEFAULT 0,
    last_override_at TEXT,
    enabled          INTEGER DEFAULT 1
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE notifications (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    session_id TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'normal',
    status TEXT NOT NULL DEFAULT 'pending',
    options TEXT,
    answer TEXT,
    answered_by TEXT,
    answered_at TEXT,
    channels_delivered TEXT DEFAULT '[]',
    telegram_message_id TEXT,
    telegram_chat_id TEXT,
    created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    expires_at TEXT,
    metadata TEXT DEFAULT '{}'
, target_kind TEXT, target_id TEXT, redeliver_at TEXT, redelivery_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE plans (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    task_id TEXT NOT NULL,
    session_id TEXT,
    impl_session_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    content TEXT NOT NULL,
    feedback TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    parent_plan_id TEXT,
    model TEXT,
    created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    reviewed_at TEXT
, plan_type TEXT DEFAULT 'generic',
    PRIMARY KEY (_scope, id)
);

CREATE TABLE review_loop_attempts (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    loop_id TEXT NOT NULL,
    iteration INTEGER NOT NULL,
    role TEXT NOT NULL,
    attempt_no INTEGER NOT NULL DEFAULT 1,
    run_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'dispatching',
    spend_usd DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    verdict TEXT,
    detail TEXT,
    created_at TEXT NOT NULL,
    settled_at TEXT
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE review_loops (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    title TEXT NOT NULL DEFAULT '',
    session_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    failure_reason TEXT,
    goal_prompt TEXT NOT NULL,
    verifier_prompt TEXT NOT NULL,
    criteria_adoption TEXT NOT NULL DEFAULT 'no',
    criteria TEXT NOT NULL DEFAULT '[]',
    implementer TEXT NOT NULL DEFAULT '{}',
    verifier TEXT NOT NULL DEFAULT '{}',
    cwd TEXT,
    max_iterations INTEGER NOT NULL DEFAULT 3,
    budget_usd DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    spent_usd DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    iteration INTEGER NOT NULL DEFAULT 0,
    current_run_id TEXT,
    escalation_count INTEGER NOT NULL DEFAULT 0,
    discovery_rounds INTEGER NOT NULL DEFAULT 0,
    warned_at TEXT,
    created_by TEXT NOT NULL DEFAULT 'user',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    ended_at TEXT
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE session_events (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    details TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE session_file_snapshots (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    session_id TEXT NOT NULL,
    file_path TEXT NOT NULL,
    original_content TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (_scope, session_id, file_path)
);

CREATE TABLE session_native_threads (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
            backend TEXT NOT NULL,
            native_thread_id TEXT NOT NULL,
            session_id TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
            updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
            PRIMARY KEY (_scope, backend, native_thread_id),
            UNIQUE (_scope, backend, session_id)
        );

CREATE TABLE session_usage (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            session_id TEXT NOT NULL,
            input_tokens INTEGER NOT NULL DEFAULT 0,
            output_tokens INTEGER NOT NULL DEFAULT 0,
            cache_creation_input_tokens INTEGER NOT NULL DEFAULT 0,
            cache_read_input_tokens INTEGER NOT NULL DEFAULT 0,
            max_context_tokens INTEGER NOT NULL DEFAULT 200000,
            created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')), model TEXT, cost_usd DOUBLE PRECISION, duration_ms INTEGER, duration_api_ms INTEGER, num_turns INTEGER DEFAULT 1, web_search_requests INTEGER NOT NULL DEFAULT 0, web_fetch_requests INTEGER NOT NULL DEFAULT 0, cache_creation_5m_input_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_1h_input_tokens INTEGER NOT NULL DEFAULT 0, cost_basis TEXT NOT NULL DEFAULT 'unknown', estimated_cost_usd DOUBLE PRECISION
        ,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE session_wakeups (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            session_id TEXT NOT NULL,
            prompt      TEXT NOT NULL,
            reason      TEXT NOT NULL DEFAULT '',
            fire_at     TEXT NOT NULL,
            status      TEXT NOT NULL DEFAULT 'pending',
            created_at  TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
        ,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE sessions (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    title TEXT,
    created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    source TEXT,
    metadata TEXT DEFAULT '{}'
, status TEXT NOT NULL DEFAULT 'idle', sdk_session_id TEXT, parent_session_id TEXT, forked_from_message TEXT, connected_at TEXT, last_activity_at TEXT, archived_at TEXT, message_count INTEGER DEFAULT 0, total_cost_usd DOUBLE PRECISION DEFAULT 0.0, last_memorized_at TEXT, starred INTEGER NOT NULL DEFAULT 0, model TEXT, backend TEXT, cwd TEXT, created_by_actor_id TEXT,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE skill_usage (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    skill_id TEXT NOT NULL,
    session_id TEXT,
    invoked_by TEXT NOT NULL,
    duration_ms INTEGER,
    success INTEGER DEFAULT 1,
    error TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE skills (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    version TEXT DEFAULT '1.0.0',
    enabled INTEGER DEFAULT 1,
    user_invocable INTEGER DEFAULT 1,
    model_invocable INTEGER DEFAULT 1,
    allowed_tools TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE source_messages (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT NOT NULL,
    source TEXT NOT NULL,
    record_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    processed_content TEXT,
    timestamp TEXT NOT NULL,
    metadata TEXT,
    run_session_id TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    expires_at TEXT NOT NULL, raw_content TEXT,
    PRIMARY KEY (_scope, source, id)
,
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE source_run_log (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    source TEXT NOT NULL,
    ran_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    records_fetched INTEGER DEFAULT 0,
    records_processed INTEGER DEFAULT 0,
    error TEXT
, session_id TEXT,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE sync_cursors (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    source TEXT,
    cursor TEXT,
    updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
,
    PRIMARY KEY (_scope, source)
);

CREATE TABLE task_events (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    task_id TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT NOT NULL,
    actor TEXT NOT NULL DEFAULT 'system',
    created_at TEXT NOT NULL
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE task_statuses (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
            name TEXT,
            label       TEXT NOT NULL,
            color       TEXT NOT NULL DEFAULT '#6b7280',
            description TEXT NOT NULL DEFAULT '',
            is_system   INTEGER NOT NULL DEFAULT 0,
            sort_order  INTEGER NOT NULL DEFAULT 0,
            created_at  TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
        ,
    PRIMARY KEY (_scope, name)
);

CREATE TABLE tasks (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    file_path TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    source TEXT,
    source_url TEXT,
    deadline TEXT,
    created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    updated_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    escalation_level INTEGER DEFAULT 0,
    last_reminded_at TEXT
, tags TEXT DEFAULT '', position DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (_scope, id),
    content TEXT NOT NULL DEFAULT ''
);

CREATE TABLE uploaded_files (
    content BYTEA NOT NULL,
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
            id TEXT,
            session_id TEXT NOT NULL,
            filename TEXT NOT NULL,
            media_type TEXT NOT NULL,
            file_type TEXT NOT NULL,
            file_size INTEGER NOT NULL,
            disk_path TEXT NOT NULL,
            created_at TEXT DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
        ,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE workflow_runs (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),
    id TEXT,
    engine TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    spec TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    budget_usd DOUBLE PRECISION,
    spent_usd DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    warned_at TEXT,
    session_id TEXT,
    journal_dir TEXT,
    created_by TEXT NOT NULL DEFAULT 'user',
    error TEXT,
    result TEXT,
    created_at TEXT NOT NULL,
    started_at TEXT,
    finished_at TEXT,
    updated_at TEXT NOT NULL
,
    PRIMARY KEY (_scope, id)
);

CREATE TABLE tasks_fts (
    _scope TEXT NOT NULL DEFAULT current_setting('nerve.scope'),task_id TEXT, title TEXT, content TEXT,
    PRIMARY KEY (_scope, task_id)
);

ALTER TABLE accounts ADD FOREIGN KEY (_scope, actor_id) REFERENCES actor_refs (_scope, id) ;

ALTER TABLE channel_sessions ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ;

ALTER TABLE messages ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ;

ALTER TABLE messages ADD FOREIGN KEY (_scope, actor_id) REFERENCES actor_refs (_scope, id) ;

ALTER TABLE review_loop_attempts ADD FOREIGN KEY (_scope, loop_id) REFERENCES review_loops (_scope, id) ON DELETE CASCADE;

ALTER TABLE review_loops ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ON DELETE SET NULL (session_id);

ALTER TABLE session_events ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ;

ALTER TABLE session_native_threads ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE session_usage ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id);

ALTER TABLE session_wakeups ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ON DELETE CASCADE;

ALTER TABLE sessions ADD FOREIGN KEY (_scope, created_by_actor_id) REFERENCES actor_refs (_scope, id) ;

ALTER TABLE workflow_runs ADD FOREIGN KEY (_scope, session_id) REFERENCES sessions (_scope, id) ON DELETE SET NULL (session_id);

CREATE UNIQUE INDEX idx_accounts_username
    ON accounts (_scope, lower(username));

CREATE UNIQUE INDEX idx_actor_refs_one_system
    ON actor_refs (_scope, kind) WHERE kind = 'system';

CREATE INDEX idx_audit_log_action ON memu_audit_log (_scope, action);

CREATE INDEX idx_audit_log_timestamp ON memu_audit_log (_scope, timestamp);

CREATE INDEX idx_cron_logs_job ON cron_logs (_scope, job_id, started_at);

CREATE INDEX idx_cron_logs_started
            ON cron_logs (_scope, started_at DESC);

CREATE INDEX idx_file_snapshots_session
    ON session_file_snapshots (_scope, session_id);

CREATE INDEX idx_mcp_tool_usage_server ON mcp_tool_usage (_scope, server_name, created_at);

CREATE INDEX idx_mcp_tool_usage_session ON mcp_tool_usage (_scope, session_id, created_at);

CREATE UNIQUE INDEX idx_messages_external_id
           ON messages (_scope, session_id, external_id)
           WHERE external_id IS NOT NULL;

CREATE INDEX idx_messages_native_turn
            ON messages (_scope, session_id, native_turn_id)
            WHERE native_turn_id IS NOT NULL;

CREATE INDEX idx_messages_session ON messages (_scope, session_id, created_at);

CREATE INDEX idx_messages_session_created
            ON messages (_scope, session_id, created_at DESC, id DESC);

CREATE INDEX idx_native_threads_session
            ON session_native_threads (_scope, session_id);

CREATE INDEX idx_notification_silences_active
    ON notification_silences (_scope, enabled, expires_at);

CREATE INDEX idx_notifications_redeliver ON notifications (_scope, status, redeliver_at);

CREATE INDEX idx_notifications_session ON notifications (_scope, session_id);

CREATE INDEX idx_notifications_status ON notifications (_scope, status, created_at DESC);

CREATE INDEX idx_notifications_target ON notifications (_scope, target_kind, target_id);

CREATE INDEX idx_plans_status ON plans (_scope, status);

CREATE INDEX idx_plans_task ON plans (_scope, task_id);

CREATE INDEX idx_review_loop_attempts_loop
    ON review_loop_attempts (_scope, loop_id, iteration, role, attempt_no);

CREATE INDEX idx_review_loops_session
    ON review_loops (_scope, session_id);

CREATE INDEX idx_review_loops_status
    ON review_loops (_scope, status, created_at DESC);

CREATE INDEX idx_session_events_session ON session_events (_scope, session_id, created_at);

CREATE INDEX idx_session_usage_created ON session_usage (_scope, created_at);

CREATE INDEX idx_session_usage_session ON session_usage (_scope, session_id);

CREATE INDEX idx_session_wakeups_due
               ON session_wakeups (_scope, status, fire_at);

CREATE INDEX idx_session_wakeups_session
               ON session_wakeups (_scope, session_id);

CREATE INDEX idx_sessions_parent ON sessions (_scope, parent_session_id);

CREATE INDEX idx_sessions_sdk_id ON sessions (_scope, sdk_session_id);

CREATE INDEX idx_sessions_status ON sessions (_scope, status);

CREATE INDEX idx_sessions_updated ON sessions (_scope, updated_at DESC);

CREATE INDEX idx_skill_usage_skill ON skill_usage (_scope, skill_id, created_at);

CREATE INDEX idx_source_messages_created ON source_messages (_scope, created_at DESC);

CREATE INDEX idx_source_messages_expires ON source_messages (_scope, expires_at);

CREATE INDEX idx_source_messages_ts ON source_messages (_scope, source, timestamp DESC);

CREATE INDEX idx_source_run_log_source ON source_run_log (_scope, source, ran_at DESC);

CREATE INDEX idx_task_events_created
    ON task_events (_scope, created_at);

CREATE INDEX idx_task_events_task
    ON task_events (_scope, task_id, created_at);

CREATE INDEX idx_tasks_deadline ON tasks (_scope, deadline);

CREATE INDEX idx_tasks_source_url ON tasks (_scope, source_url);

CREATE INDEX idx_tasks_status ON tasks (_scope, status);

CREATE INDEX idx_tasks_status_position ON tasks (_scope, status, position);

CREATE INDEX idx_uploaded_files_session
            ON uploaded_files (_scope, session_id);

CREATE INDEX idx_workflow_runs_session
    ON workflow_runs (_scope, session_id);

CREATE INDEX idx_workflow_runs_status
    ON workflow_runs (_scope, status, created_at DESC);

CREATE UNIQUE INDEX uq_review_loop_attempts_run
    ON review_loop_attempts (_scope, run_id);

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

ALTER TABLE accounts FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON accounts USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE actor_refs ENABLE ROW LEVEL SECURITY;

ALTER TABLE actor_refs FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON actor_refs USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE channel_sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE channel_sessions FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON channel_sessions USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE consumer_cursors ENABLE ROW LEVEL SECURITY;

ALTER TABLE consumer_cursors FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON consumer_cursors USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE cron_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE cron_logs FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON cron_logs USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE instance_secrets ENABLE ROW LEVEL SECURITY;

ALTER TABLE instance_secrets FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON instance_secrets USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE instance_setup ENABLE ROW LEVEL SECURITY;

ALTER TABLE instance_setup FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON instance_setup USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE mcp_servers ENABLE ROW LEVEL SECURITY;

ALTER TABLE mcp_servers FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON mcp_servers USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE mcp_tool_usage ENABLE ROW LEVEL SECURITY;

ALTER TABLE mcp_tool_usage FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON mcp_tool_usage USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE memu_audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE memu_audit_log FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON memu_audit_log USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE messages FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON messages USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE notification_silences ENABLE ROW LEVEL SECURITY;

ALTER TABLE notification_silences FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON notification_silences USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE notifications FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON notifications USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE plans ENABLE ROW LEVEL SECURITY;

ALTER TABLE plans FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON plans USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE review_loop_attempts ENABLE ROW LEVEL SECURITY;

ALTER TABLE review_loop_attempts FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON review_loop_attempts USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE review_loops ENABLE ROW LEVEL SECURITY;

ALTER TABLE review_loops FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON review_loops USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE session_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE session_events FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON session_events USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE session_file_snapshots ENABLE ROW LEVEL SECURITY;

ALTER TABLE session_file_snapshots FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON session_file_snapshots USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE session_native_threads ENABLE ROW LEVEL SECURITY;

ALTER TABLE session_native_threads FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON session_native_threads USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE session_usage ENABLE ROW LEVEL SECURITY;

ALTER TABLE session_usage FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON session_usage USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE session_wakeups ENABLE ROW LEVEL SECURITY;

ALTER TABLE session_wakeups FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON session_wakeups USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE sessions FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON sessions USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE skill_usage ENABLE ROW LEVEL SECURITY;

ALTER TABLE skill_usage FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON skill_usage USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

ALTER TABLE skills FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON skills USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE source_messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE source_messages FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON source_messages USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE source_run_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE source_run_log FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON source_run_log USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE sync_cursors ENABLE ROW LEVEL SECURITY;

ALTER TABLE sync_cursors FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON sync_cursors USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE task_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE task_events FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON task_events USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE task_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE task_statuses FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON task_statuses USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

ALTER TABLE tasks FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON tasks USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE uploaded_files ENABLE ROW LEVEL SECURITY;

ALTER TABLE uploaded_files FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON uploaded_files USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE workflow_runs ENABLE ROW LEVEL SECURITY;

ALTER TABLE workflow_runs FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON workflow_runs USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE tasks_fts ENABLE ROW LEVEL SECURITY;

ALTER TABLE tasks_fts FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON tasks_fts USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE tasks_fts ADD COLUMN document tsvector GENERATED ALWAYS AS
    (setweight(to_tsvector('simple',coalesce(title,'')),'A') || setweight(to_tsvector('simple',coalesce(task_id,'')),'B') || to_tsvector('simple',coalesce(content,''))) STORED;
CREATE INDEX tasks_document ON tasks_fts USING gin(document);
CREATE FUNCTION datetime(value text) RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(value::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
$$;
CREATE FUNCTION datetime(value text, modifier text) RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char((value::timestamptz + modifier::interval) AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
$$;
CREATE FUNCTION protect_actor() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME = 'accounts' THEN
        IF NOT EXISTS (SELECT 1 FROM actor_refs WHERE id=NEW.actor_id AND kind='human') THEN
            RAISE EXCEPTION 'accounts.actor_id must reference a human actor_ref' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'actor identities cannot be deleted' USING ERRCODE='23514';
    END IF;
    IF OLD.kind='system' AND (NEW.kind IS DISTINCT FROM OLD.kind OR NEW.id IS DISTINCT FROM OLD.id) THEN
        RAISE EXCEPTION 'system actor identity is immutable' USING ERRCODE='23514';
    END IF;
    IF NEW.kind!='human' AND EXISTS (SELECT 1 FROM accounts WHERE actor_id=OLD.id) THEN
        RAISE EXCEPTION 'referenced actor must stay human' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER account_actor BEFORE INSERT OR UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION protect_actor();
CREATE TRIGGER actor_identity BEFORE UPDATE OR DELETE ON actor_refs FOR EACH ROW EXECUTE FUNCTION protect_actor();
CREATE TABLE task_reservations (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'), id text NOT NULL,
    PRIMARY KEY (_scope,id)
);
ALTER TABLE task_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_reservations FORCE ROW LEVEL SECURITY;
CREATE POLICY scope ON task_reservations USING (_scope=current_setting('nerve.scope', true));
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE resources (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'),
    id VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    url VARCHAR NOT NULL,
    modality VARCHAR NOT NULL,
    local_path VARCHAR NOT NULL,
    caption TEXT,
    embedding VECTOR,
    PRIMARY KEY (_scope, id)
);

CREATE INDEX ix_resources_id ON resources (_scope, id);

CREATE TABLE memory_categories (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'),
    id VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL,
    embedding VECTOR,
    summary TEXT,
    PRIMARY KEY (_scope, id)
);

CREATE INDEX ix_memory_categories_name ON memory_categories (_scope, name);

CREATE INDEX ix_memory_categories_id ON memory_categories (_scope, id);

CREATE TABLE memory_items (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'),
    id VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resource_id VARCHAR,
    memory_type VARCHAR NOT NULL,
    summary TEXT NOT NULL,
    embedding VECTOR,
    happened_at TIMESTAMP WITHOUT TIME ZONE,
    extra JSONB,
    PRIMARY KEY (_scope, id),
    FOREIGN KEY(_scope, resource_id) REFERENCES resources (_scope, id) ON DELETE CASCADE
);

CREATE INDEX ix_memory_items_id ON memory_items (_scope, id);

CREATE TABLE category_items (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'),
    id VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    item_id VARCHAR NOT NULL,
    category_id VARCHAR NOT NULL,
    PRIMARY KEY (_scope, id),
    FOREIGN KEY(_scope, item_id) REFERENCES memory_items (_scope, id) ON DELETE CASCADE,
    FOREIGN KEY(_scope, category_id) REFERENCES memory_categories (_scope, id) ON DELETE CASCADE
);

CREATE INDEX ix_category_items_id ON category_items (_scope, id);

CREATE UNIQUE INDEX idx_category_items_unique ON category_items (_scope, item_id, category_id);

ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

ALTER TABLE resources FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON resources USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE memory_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE memory_items FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON memory_items USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE memory_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE memory_categories FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON memory_categories USING (_scope=current_setting('nerve.scope', true));

ALTER TABLE category_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE category_items FORCE ROW LEVEL SECURITY;

CREATE POLICY scope ON category_items USING (_scope=current_setting('nerve.scope', true));

CREATE TABLE resource_blobs (
    _scope text NOT NULL DEFAULT current_setting('nerve.scope'),
    resource_id text NOT NULL, content bytea NOT NULL,
    PRIMARY KEY (_scope,resource_id),
    FOREIGN KEY (_scope,resource_id) REFERENCES resources(_scope,id) ON DELETE CASCADE
);
ALTER TABLE resource_blobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE resource_blobs FORCE ROW LEVEL SECURITY;
CREATE POLICY scope ON resource_blobs USING (_scope=current_setting('nerve.scope', true));
CREATE FUNCTION instr(value jsonb, needle text) RETURNS integer LANGUAGE sql IMMUTABLE AS $$
    SELECT strpos(value::text,needle)
$$;
COMMIT;
