"""Pin the Claude CLI's credential store to the file backend (macOS).

Claude Code keeps OAuth credentials — its own login and every MCP plugin's
tokens — in ONE of two stores, chosen per process at runtime: the macOS
Keychain when the process's security session can read the login keychain,
otherwise ``~/.claude/.credentials.json``. A long-running service inherits
that choice from whoever launched it: a gateway started from Terminal reads
the Keychain, one started from an SSH, agent or background context reads the
file. Refresh tokens rotate (single use), so whichever store performed the
latest refresh holds the only valid one and the other store's copy goes stale
without anyone noticing. The first session after a launch-context flip then
fails its refresh with ``invalid_grant`` and the CLI deletes the entry —
every session reports "needs authentication" until a human re-authorizes.

``agent.claude_credential_store: file`` removes the flip. The CLI probes the
Keychain by spawning ``security find-generic-password … -s "Claude Code…"``
through a shell, by name, so a ``security`` shim placed first on the
subprocess PATH decides the outcome: for the CLI's own items it answers the
way a locked keychain does (exit 36, "User interaction is not allowed"),
which the CLI already handles by falling back to the file store; every other
invocation is handed to ``/usr/bin/security`` untouched, so an agent's own
use of the tool keeps working. The shim lives at ``$NERVE_HOME/bin/security``
and is (re)generated whenever a client environment is built.
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from pathlib import Path

from nerve import paths

SHIM_DIRNAME = "bin"
SHIM_NAME = "security"
SHIM_VERSION = 1
# Every service name the CLI stores credentials under starts with this.
CLI_SERVICE_PREFIX = "Claude Code"
REAL_SECURITY = "/usr/bin/security"

SHIM_SCRIPT = f"""#!/bin/sh
# Nerve credential-store shim v{SHIM_VERSION} (agent.claude_credential_store: file).
# Generated by nerve.agent.credential_store — edits are overwritten.
#
# The Claude CLI keeps its OAuth tokens in the macOS Keychain whenever this
# tool can read the login keychain, and in ~/.claude/.credentials.json
# otherwise. Answer the CLI's own items the way a locked keychain would, so
# the CLI always takes the file path; hand everything else to the real tool.
for arg in "$@"; do
  case "$arg" in
    "{CLI_SERVICE_PREFIX}"*)
      echo "security: SecKeychainSearchCopyNext: User interaction is not allowed." >&2
      exit 36
      ;;
  esac
done
exec {REAL_SECURITY} "$@"
"""


def shim_dir(home: Path | None = None) -> Path:
    """Directory the shim lives in (``$NERVE_HOME/bin`` by default)."""
    base = home if home is not None else paths.nerve_home()
    return base / SHIM_DIRNAME


def ensure_security_shim(directory: Path) -> Path:
    """Write the ``security`` shim into *directory* (idempotent) and return it.

    The script is written atomically (temp file + rename) so a client that is
    being built concurrently never executes a half-written file, and it is
    rewritten whenever its content differs from the current template.
    """
    directory.mkdir(parents=True, exist_ok=True)
    shim = directory / SHIM_NAME
    if shim.is_file() and os.access(shim, os.X_OK):
        with contextlib.suppress(OSError):
            if shim.read_text() == SHIM_SCRIPT:
                return shim
    fd, tmp_name = tempfile.mkstemp(dir=directory, prefix=f".{SHIM_NAME}.")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(SHIM_SCRIPT)
        os.chmod(tmp_name, 0o755)
        os.replace(tmp_name, shim)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp_name)
        raise
    return shim


def prepend_to_path(path_value: str | None, directory: Path) -> str:
    """Return *path_value* with *directory* as its first entry, exactly once."""
    wanted = str(directory)
    entries = [e for e in (path_value or "").split(os.pathsep) if e and e != wanted]
    return os.pathsep.join([wanted, *entries])


def file_store_env(
    path_value: str | None = None, home: Path | None = None
) -> dict[str, str]:
    """Environment overrides that pin the CLI subprocess to the file store.

    Installs the shim under ``shim_dir(home)`` and returns ``{"PATH": ...}``
    with that directory first. *path_value* defaults to the current
    process's ``PATH``.
    """
    directory = shim_dir(home)
    ensure_security_shim(directory)
    base = path_value if path_value is not None else os.environ.get("PATH", "")
    return {"PATH": prepend_to_path(base, directory)}
