"""Renderer tests — verify the bundles look right.

We render each style into a fixture workspace, then assert the output
contains every source section *and* the mandatory-first-action note.
Tests don't compare full strings (too brittle) — they look for the
load-bearing markers.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from nerve.external_agents.registry import FileTarget
from nerve.external_agents.renderers import get_renderer
from nerve.external_agents.renderers.claude_code import ClaudeCodeRenderer
from nerve.external_agents.renderers.codex_global import CodexGlobalRenderer
from nerve.external_agents.renderers.passthrough import PassthroughRenderer


@pytest.fixture
def workspace(tmp_path: Path) -> Path:
    """Tiny workspace with one section per identity file."""
    (tmp_path / "SOUL.md").write_text("# SOUL\n\nMy soul lives here.\n")
    (tmp_path / "IDENTITY.md").write_text("# IDENTITY\n\nName: Robot.\n")
    (tmp_path / "USER.md").write_text("# USER\n\nName: Alice.\n")
    (tmp_path / "TOOLS.md").write_text("# TOOLS\n\nCameras, SSH, ...\n")
    (tmp_path / "MEMORY.md").write_text("# MEMORY\n\nActive context.\n")
    (tmp_path / "AGENTS.md").write_text("# AGENTS\n\nWorkspace conventions.\n")
    return tmp_path


def test_codex_global_bundles_everything(workspace: Path) -> None:
    target = FileTarget(
        output=Path("~/.codex/AGENTS.md").expanduser(),
        includes=["SOUL.md", "IDENTITY.md", "USER.md", "TOOLS.md", "MEMORY.md"],
        style="codex-global",
    )
    rendered = CodexGlobalRenderer().render(target, workspace=workspace)

    # Top-level framing
    assert "Generated by Nerve" in rendered
    assert "Mandatory First Action" in rendered
    assert "session_context(" in rendered

    # Every source file's content shows up
    for marker in ("My soul lives here.", "Name: Robot.", "Name: Alice.",
                   "Cameras, SSH", "Active context."):
        assert marker in rendered

    # File-name headings preserved
    assert "# SOUL.md" in rendered
    assert "# MEMORY.md" in rendered


def test_codex_global_skips_missing_files(workspace: Path) -> None:
    # Reference a non-existent TASK.md — must NOT crash.
    target = FileTarget(
        output=Path("~/.codex/AGENTS.md").expanduser(),
        includes=["SOUL.md", "TASK.md", "USER.md"],
        style="codex-global",
    )
    rendered = CodexGlobalRenderer().render(target, workspace=workspace)
    assert "My soul lives here." in rendered
    assert "Name: Alice." in rendered
    # No TASK.md section
    assert "# TASK.md" not in rendered


def test_claude_code_bundles_full_set(workspace: Path) -> None:
    target = FileTarget(
        output=Path("~/.claude/CLAUDE.md").expanduser(),
        includes=["SOUL.md", "IDENTITY.md", "USER.md", "AGENTS.md", "TOOLS.md", "MEMORY.md"],
        style="claude-code",
    )
    rendered = ClaudeCodeRenderer().render(target, workspace=workspace)
    assert "CLAUDE.md — Generated by Nerve" in rendered
    assert "Workspace conventions." in rendered  # AGENTS.md is included here
    assert "session_context(" in rendered


def test_passthrough_renderer(workspace: Path) -> None:
    target = FileTarget(
        output=workspace / "out.md",
        includes=["SOUL.md", "USER.md"],
        style="passthrough",
    )
    rendered = PassthroughRenderer().render(target, workspace=workspace)
    assert "My soul lives here." in rendered
    assert "Name: Alice." in rendered
    # Passthrough has no header
    assert "Generated by Nerve" not in rendered


def test_get_renderer_falls_back_for_unknown_style() -> None:
    """Unknown styles should resolve to passthrough so a sync sweep
    can't crash because of a misconfigured target."""
    renderer = get_renderer("not-a-real-style")
    assert isinstance(renderer, PassthroughRenderer)


def test_workspace_path_appears_in_codex_footer(workspace: Path) -> None:
    target = FileTarget(
        output=Path("~/.codex/AGENTS.md").expanduser(),
        includes=["SOUL.md"],
        style="codex-global",
    )
    rendered = CodexGlobalRenderer().render(target, workspace=workspace)
    assert str(workspace) in rendered
